name: Grow
on:
  gollum
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare your file
      run: |
        mkdir download
        git clone "https://github.com/muhammetm/Grow.wiki.git"
        wiki=`echo $echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki

